with open('index.html', 'r', encoding='utf-8') as f: content = f.read()
content = content.replace('overflow-x-auto', 'w-full')
with open('index.html', 'w', encoding='utf-8') as f: f.write(content)

with open('js/app.js', 'r', encoding='utf-8') as f: content = f.read()
content = content.replace('overflow-x-auto', 'w-full')
content = content.replace('<table class="w-full text-xs border-collapse">', '<table class="w-full text-[10px] border-collapse">')
content = content.replace('<th class="py-2 px-3 text-left bg-slate-600 sticky left-0 z-20 w-44">Metric</th>', '<th class="py-1 px-1 text-left bg-slate-600 sticky left-0 z-20 w-32">Metric</th>')
content = content.replace('class="py-2 px-2 bg-slate-500', 'class="py-1 px-1 bg-slate-500')
content = content.replace('class="py-2 px-2 bg-cyan-700', 'class="py-1 px-1 bg-cyan-700')
content = content.replace('class="py-1 px-3 text-left sticky left-0 bg-slate-100 z-20"', 'class="py-1 px-1 text-left sticky left-0 bg-slate-100 z-20"')
content = content.replace('<th class="py-1 px-2">', '<th class="py-1 px-1">')
content = content.replace('class="py-1 px-2 bg-cyan-50', 'class="py-1 px-1 bg-cyan-50')
content = content.replace('class="py-1.5 px-3 text-left sticky left-0', 'class="py-1 px-1 text-left sticky left-0')
content = content.replace('class="py-1.5 px-2 text-right', 'class="py-1 px-1 text-right')
with open('js/app.js', 'w', encoding='utf-8') as f: f.write(content)
